In [121]:
import numpy as np
path = "input.txt"
path = "example.txt"
input = [[*map(int, list(x))] for x in open(path).read().splitlines()]
input = np.array(input, dtype=np.int64)
counted = np.ones(input.shape, dtype=np.int64)
print(input)
# print(counted)

def check(row, c_row):
    highest = -1
    count = 0
    for i,x in enumerate(row):
        if x > highest:
            count += c_row[i]
            c_row[i] = 0
            highest = x

    return count

p1 = 0 
for r,row in enumerate(input):
    c_row = counted[r]
    # print(row, c_row)
    p1 += check(row, c_row)
    p1 += check(row[::-1], c_row[::-1])

for r,row in enumerate(input.T):
    c_row = counted.T[r]
    # print(row, c_row)
    p1 += check(row, c_row)
    p1 += check(row[::-1], c_row[::-1])

# print(check(input[0],counted[0]))
# print(input, counted)
print(p1)

[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]
21


In [156]:
import numpy as np
path = "input.txt"
# path = "example.txt"
input = [[*map(int, list(x))] for x in open(path).read().splitlines()]
input = np.array(input, dtype=np.int64)
counted = np.ones(input.shape, dtype=np.int64)
# print(input)
# print(counted)

def check(row, c_row):
    inds = np.append(np.diff(np.maximum.accumulate(row)).nonzero()[0]+1,[0])
    count_mask = c_row[inds]
    count = np.count_nonzero(count_mask)

    c_row[inds] = 0
    return count

p1 = 0 
for r,row in enumerate(input):
    c_row = counted[r]
    # print(row, c_row)
    p1 += check(row, c_row)
    p1 += check(row[::-1], c_row[::-1])

for r,row in enumerate(input.T):
    c_row = counted.T[r]
    # print(row, c_row)
    p1 += check(row, c_row)
    p1 += check(row[::-1], c_row[::-1])

# print(check(input[0],counted[0]))
# print(input, counted)
print(p1)

1807


In [123]:
import numpy as np
path = "input.txt"
path = "example.txt"
input = np.array([[*map(int, list(x))] for x in open(path).read().splitlines()])


p2 = np.empty(input.shape, dtype=np.int64)
for (r,c),h in np.ndenumerate(input):
    p2[r,c] = np.prod([d[0][0]+1 if len(d[0]) else len(row) for row in [input[r][c+1:], input[r][:c][::-1], input.T[c][r+1:], input.T[c][:r][::-1]] if (d := np.where(row >= h))])

print(np.max(p2))

8
